CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE chirps (

  -- TABLE CODE TO GO HERE
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(25) NOT NULL,
  chirp VARCHAR(300) NOT NULL,
  time_created DATETIME NOT NULL
);